<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WhatsappController extends Controller
{

    public function main(){
        $start = microtime(true);
    
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://watverifyapi.live/verify?api_key=API-X-29442328030320198524098206&phones=+923314275398');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        $result = curl_exec($ch);
        $time_elapsed_secs = microtime(true) - $start;
        logger($time_elapsed_secs);
        dd($result);
        if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
    }

    public function main2(){
        $start = microtime(true);
    
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://watverifyapi.live/verify?api_key=API-X-12753939756343038150474252&phones=+923314275398');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        $result = curl_exec($ch);
        $time_elapsed_secs = microtime(true) - $start;
        logger('Second=> '.$time_elapsed_secs);
        dd($result);
        if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
    }
}
